apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: deployment
metadata: 
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
sepc:
  replicas: 1
  selector:
    matchingLabels:
    project: roboshop
    tier: backend
    component: cart
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: cart
    containers:
      - name: cart
        image: mrudula158/cart:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu:  "100m"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodpolicy: 10
          initialDelay: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodpolicy: 10
         envFrom:
          confifMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: cart
  labels:
        project: roboshop
        tier: backend
        component: cart
spec:
  selector:
    project: roboshop
    tier: backend
    component: cart
  ports:
    protocol: TCP
    port: 8080
    targetport: 8080          


